" --------------
" DDD VIM CONFIG
" --------------

set clipboard=unnamedplus
set nocompatible
set encoding=utf8
filetype off
syntax enable

let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"

execute "set t_8f=\e[38;2;%lu;%lu;%lum"
execute "set t_8b=\e[38;2;%lu;%lu;%lum"

set ff=unix

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'Yggdroot/indentLine'
Plugin 'VundleVim/Vundle.vim' 
Plugin 'chriskempson/base16-vim'
"Plugin 'sheerun/vim-polyglot'
Plugin 'morhetz/gruvbox'
Plugin 'wincent/terminus'
Plugin 'jiangmiao/auto-pairs'
Plugin 'preservim/nerdtree'
Plugin 'sirver/ultisnips'
Plugin 'normen/vim-pio'
Plugin 'MaskRay/ccls'
Plugin 'prabirshrestha/vim-lsp'

call vundle#end()
filetype plugin indent on

set shiftwidth=2 tabstop=2 softtabstop=2 expandtab autoindent smartindent smarttab
set colorcolumn=100
highlight ColorColumn ctermbg=darkgray

colorscheme base16-gruvbox-dark-medium

set number
set nowrap
set nu
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set cursorline
set cursorcolumn
set lazyredraw
set hlsearch
set virtualedit=onemore 
"set list
"set listchars=tab:\¦\ 

set ignorecase
set smartcase 

set splitbelow
set splitright

set noexpandtab

" window navigation
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" buffers
nnoremap <C-q> :buffers<CR>:buffer<Space>

" copy entire file to clipboard
nnoremap <S-y> :%y+<CR>

" IT MUST BE TAUGHT
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

" plugin specific 
map <C-n> :NERDTreeToggle<CR>

" wgsl
autocmd BufNewFile,BufRead *.wgsl set syntax=rust

" compiling
nnoremap <F4> :!pandoc %:p -r org -w pdf -o output.pdf<CR>
