" --------------
" DDD VIM CONFIG
" --------------

set nocompatible
set encoding=utf8
filetype off
syntax enable

let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"

execute "set t_8f=\e[38;2;%lu;%lu;%lum"
execute "set t_8b=\e[38;2;%lu;%lu;%lum"


set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'Yggdroot/indentLine'
Plugin 'VundleVim/Vundle.vim' 
Plugin 'chriskempson/base16-vim'
Plugin 'sheerun/vim-polyglot'
Plugin 'morhetz/gruvbox'
Plugin 'wincent/terminus'
Plugin 'jiangmiao/auto-pairs'
Plugin 'preservim/nerdtree'
Plugin 'lervag/vimtex', {'tex_flavor': 'latex', 'vimtex_view_method': 'zathura', 'vimtex_quickfix_mode': 0, 'conceallevel': 1, 'tex_conceal': 'abdmg'}
Plugin 'sirver/ultisnips'

call vundle#end()
filetype plugin indent on

set shiftwidth=2 tabstop=2 softtabstop=2 expandtab autoindent smartindent smarttab
set colorcolumn=100
highlight ColorColumn ctermbg=darkgray

colorscheme base16-gruvbox-dark-medium

set number
set nowrap
set nu
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set relativenumber
set cursorline
set lazyredraw
set hlsearch
set virtualedit=onemore 

set ignorecase
set smartcase 

set splitbelow
set splitright

" window navigation
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" plugin specific 
map <C-n> :NERDTreeToggle<CR>

